### PR TITLE
Improve handling of tags

### PR DESCRIPTION
**Pull request by tbm**

### CODE REVIEW

**Comment by tbm** [comment]
tag_as_metadata is a workaround, so I don't think we need another option.  "tag" in ledger means tag or link, so tag_as_metadata is fine.  I don't see why they would be handled in a different way.

This just makes link_match work when tag_as_metadata is enabled.  Previously it put everything as "tags" metadata. Now you get "tags" and "links".

If you don't want that, don't set link_match

**Comment by zacchiro** [comment]
I'm ok with most of this PR, apart from a couple of nits on two commits - see separate comments. But since it's a single PR I can't easily merge the rest of it. Sorry :)

**Comment by zacchiro** [comment]
Ok. Fair enough on the separate option

**Comment by tbm** [comment]
The problem with the blank line sucks but I dont' see how to avoid it.

In ledger, I add
```
line 1
line 2
blank line to separate
```
In this case, line 1 and line 2 are ignored.  So only the empty line is written to beancount.

However, I don't think the script should start ignoring blank lines.  Although I guess we could check for an empty line after a stanza (optional).

**Comment by tbm** [comment]
Anyway, if you think ignoring an empty line after a stanza we ignore, I can add a patch but I'll do it in a separate PR so not to delay this one :)

**Comment by zacchiro** [comment]
I don't care that much about the extra line, I was pointing it out in case it was something simple and/or overlooked; so don't bother investing time into that. This PR is good to go.

**Pull request merged**
