### PR TITLE
allow commodities to be treated as currencies

### LINKED ISSUE #37: allow commodity to be treated as currency for conversion, i.e. don't keep costs
We need the opposite of `commodities3char`, i.e. treat a commodity as if it was a currency, i.e. don't keep the cost around.  This is useful for e.g. air miles.

### PR DESCRIPTION
**Pull request by tbm**
Fixes #37

### CODE REVIEW

**Comment by tbm** [comment]
> actually there it might make sense to retain the cost.

That is a bogus argument because that's exactly what `commodity_is_currency` is wrong.

However, the more I think about it, the more I believe we should only look at the 1st commodity, not at the lot price.

Because we're trying to answer: should we preserve a cost price for THIS commodity:

Some examples (ledger):

```
2017-04-11 * Convert AMEX MR to KrisFlyer miles
    Assets:Transfer             1 KrisFlyer @@ 1 MR
    Assets:Rewards                            -1 MR

2017-04-11 * Use AMEX MR to pay credit card
    Assets:Transfer                0.01 USD @@ 1 MR
    Assets:Rewards                            -1 MR

; In beancount I'd probably reformat to do this:

2017-04-11 * Convert AMEX MR to KrisFlyer miles
    Assets:Transfer                     1 KrisFlyer
    Assets:Rewards             -1 MR @@ 1 KrisFlyer

2017-04-11 * Use AMEX MR to pay credit card
    Assets:Transfer                        0.01 USD
    Assets:Rewards                -1 MR @@ 0.01 USD
```

how should they be converted?  I think:

```
2017-04-11 open Assets:Transfer
2017-04-11 open Assets:Rewards
2017-04-11 open Expenses:Whatever


2017-04-11 * "Convert AMEX MR to KrisFlyer miles"
    Assets:Transfer             1 KRISFLYER @@ 1 MR
    Assets:Rewards                            -1 MR

2017-04-11 * "Use AMEX MR to pay credit card"
    Assets:Transfer                0.01 USD @@ 1 MR
    Assets:Rewards                            -1 MR

2017-04-11 * "Convert AMEX MR to KrisFlyer miles"
    Assets:Transfer                     1 KRISFLYER
    Assets:Rewards             -1 MR @@ 1 KRISFLYER

2017-04-11 * "Convert AMEX MR to KrisFlyer miles"
    Assets:Transfer                        0.01 USD
    Assets:Rewards                -1 MR @@ 0.01 USD  ; or maybe -1 MR {0.01 USD}
```

Note the `or maybe`.  This is bogus: what I really want is the *price* in the pricedb, but this is done via @@ and implicit prices anyway.

Sure, if some users may want to retain the cost for MR, but then it would be the case both for 1 MR @ USD and ! MR @ KRISFLYER.  Which again suggests we only need to look at the left price.

But since we already look at both prices, this PR doesn't make things worse.  I think it should be accepted.  And if I'm right, we can add a patch later to only look at the left side.

**Comment by zacchiro** [comment]
Aside from the conflicts to be resolved, the judgement call here is above my pay grade :), as I don't really use any of this in Ledger/Beancount. I'll let you decide what you think is best. If you feel confident it's useful as is I'll merge it. Alternatively, I think this can be put on hold for a while, and we ask for feedback about it to other (potential) ledger/beancount users, e.g., on the beancount user group. Of course in that case we should wait to announce there, to give some initial exposure to the tool.

**Comment by tbm** [comment]
Please apply it. Should I resolve the conflicts or will you?

**Comment by zacchiro** [comment]
tried to resolve conflicts online but filed, please do it on your hand as you already have the branch locally

**Pull request merged**
